const router = require("express").Router();
const controller = require("../controllers/organizationController");
const { authMiddleware } = require("../middlewares/auth");
const { authorize } = require("../middlewares/authorize");

router.post("/", authMiddleware, controller.createOrganization);
router.post("/:organizationId/invitations", authMiddleware, controller.inviteMember);
router.post("/invitations/accept", authMiddleware, controller.acceptInvitation);
router.delete("/:organizationId/members/:userId", authMiddleware, controller.removeMember);
router.get("/:organizationId/members", authMiddleware, controller.listMembers);
router.patch("/:organizationId/settings", authMiddleware, controller.updateSettings);
router.post("/:organizationId/departments", authMiddleware, controller.createDepartment);
router.get("/:organizationId/departments", authMiddleware, controller.listDepartments);
router.patch("/departments/:departmentId", authMiddleware, controller.updateDepartment);
router.delete("/departments/:departmentId", authMiddleware, controller.deleteDepartment);
router.get("/:organizationId/analytics", authMiddleware, controller.organizationAnalytics);
router.put("/:organizationId/sso", authMiddleware, controller.upsertSso);
router.post("/contacts/requests", authMiddleware, controller.sendContactRequest);
router.post("/contacts/requests/:requesterId/respond", authMiddleware, controller.respondContactRequest);
router.post("/contacts/requests/:requesterId/block", authMiddleware, controller.blockContact);
router.get("/contacts", authMiddleware, controller.listContacts);
router.get("/contacts/pending", authMiddleware, controller.listPendingContacts);
router.get("/users/search", authMiddleware, controller.searchUsers);
router.put("/availability", authMiddleware, controller.upsertAvailability);
router.get("/availability/:handle", controller.getAvailability);
router.get("/availability/:handle/slots", controller.listSlots);
router.post("/availability/:handle/book", controller.bookSlot);
router.get("/notifications", authMiddleware, controller.listNotifications);
router.post("/notifications/:notificationId/read", authMiddleware, controller.readNotification);
router.post("/notifications/read-all", authMiddleware, controller.readAllNotifications);
router.delete("/notifications/:notificationId", authMiddleware, controller.deleteNotification);
router.get("/notification-preferences", authMiddleware, controller.preferences);
router.patch("/notification-preferences", authMiddleware, controller.updatePreferences);
router.put("/notification-preferences", authMiddleware, controller.updatePreferences);
router.post("/device-tokens", authMiddleware, controller.registerDevice);
router.delete("/device-tokens", authMiddleware, controller.unregisterDevice);
router.get("/analytics/me", authMiddleware, controller.userAnalytics);
router.get("/analytics/superadmin", authMiddleware, authorize("superadmin"), controller.superadminAnalytics);
router.post("/gdpr/requests", authMiddleware, controller.createGdprRequest);
router.get("/exports/meetings.csv", authMiddleware, controller.exportMeetingsCsv);
router.get("/exports/users.csv", authMiddleware, authorize("superadmin"), controller.exportUsersCsv);
router.get("/exports/recordings.csv", authMiddleware, controller.exportRecordingsCsv);

module.exports = router;
