import { api } from "./api";

export const meetingService = {
  list: (params) => api.get("/meetings", { params }).then((response) => response.data),
  create: (payload) => api.post("/meetings", payload).then((response) => response.data.meeting),
  get: (meetingId) => api.get(`/meetings/${meetingId}`).then((response) => response.data.meeting),
  update: (meetingId, payload) => api.patch(`/meetings/${meetingId}`, payload).then((response) => response.data.meeting),
  cancel: (meetingId) => api.post(`/meetings/${meetingId}/cancel`).then((response) => response.data.meeting),
  end: (meetingId) => api.post(`/meetings/${meetingId}/end`).then((response) => response.data.meeting),
  token: (meetingId, payload = {}) => api.post(`/meetings/${meetingId}/token`, payload).then((response) => response.data),
  waitingList: (meetingId) => api.get(`/meetings/${meetingId}/waiting-room`).then((response) => response.data.participants),
  admitWaiting: (meetingId, identity) => api.post(`/meetings/${meetingId}/waiting-room/admit`, { identity }),
  rejectWaiting: (meetingId, identity) => api.post(`/meetings/${meetingId}/waiting-room/reject`, { identity }),
  admitAllWaiting: (meetingId) => api.post(`/meetings/${meetingId}/waiting-room/admit-all`),
  participants: (meetingId) => api.get(`/meetings/${meetingId}/participants`).then((response) => response.data.participants),
  removeParticipant: (meetingId, identity) => api.post(`/meetings/${meetingId}/participants/remove`, { identity }),
  muteParticipant: (meetingId, identity, trackSid, muted) => api.post(`/meetings/${meetingId}/participants/mute`, { identity, trackSid, muted }),
  addCoHost: (meetingId, userId) => api.post(`/meetings/${meetingId}/co-hosts`, { userId }),
  removeCoHost: (meetingId, userId) => api.delete(`/meetings/${meetingId}/co-hosts/${userId}`),
  raiseHand: (meetingId) => api.post(`/meetings/${meetingId}/hands/raise`),
  lowerHand: (meetingId) => api.post(`/meetings/${meetingId}/hands/lower`),
  listHands: (meetingId) => api.get(`/meetings/${meetingId}/hands`).then((response) => response.data.hands),
  react: (meetingId, payload) => api.post(`/meetings/${meetingId}/reactions`, payload),
  createPoll: (meetingId, payload) => api.post(`/meetings/${meetingId}/polls`, payload).then((response) => response.data.poll),
  respondPoll: (pollId, payload) => api.post(`/meetings/polls/${pollId}/responses`, payload),
  pollResults: (pollId) => api.get(`/meetings/polls/${pollId}/results`).then((response) => response.data),
  endPoll: (pollId) => api.post(`/meetings/polls/${pollId}/end`).then((response) => response.data.poll),
  listQuestions: (meetingId) => api.get(`/meetings/${meetingId}/questions`).then((response) => response.data.questions),
  askQuestion: (meetingId, payload) => api.post(`/meetings/${meetingId}/questions`, payload).then((response) => response.data.question),
  answerQuestion: (questionId, payload) => api.post(`/meetings/questions/${questionId}/answer`, payload).then((response) => response.data.question),
  chatList: (meetingId) => api.get(`/meetings/${meetingId}/chat`).then((response) => response.data.messages),
  chatSend: (meetingId, payload) => api.post(`/meetings/${meetingId}/chat`, payload).then((response) => response.data.message),
  chatUpload: (meetingId, formData) => api.post(`/meetings/${meetingId}/chat/upload`, formData, { headers: { "Content-Type": "multipart/form-data" } }).then((response) => response.data.message),
  chatDelete: (messageId) => api.delete(`/meetings/chat/${messageId}`),
  chatPin: (messageId, isPinned) => api.post(`/meetings/chat/${messageId}/pin`, { isPinned }),
  whiteboardGet: (meetingId) => api.get(`/meetings/${meetingId}/whiteboard`).then((response) => response.data.whiteboard),
  whiteboardUpdate: (meetingId, canvasState) => api.put(`/meetings/${meetingId}/whiteboard`, { canvasState }).then((response) => response.data.whiteboard),
  listTemplates: () => api.get("/meetings/templates/all").then((response) => response.data.templates),
  notesList: (meetingId) => api.get(`/meetings/${meetingId}/notes`).then((response) => response.data.notes),
  noteAdd: (meetingId, content) => api.post(`/meetings/${meetingId}/notes`, { content }).then((response) => response.data.note),
  noteUpdate: (noteId, content) => api.patch(`/meetings/notes/${noteId}`, { content }).then((response) => response.data.note),
  noteDelete: (noteId) => api.delete(`/meetings/notes/${noteId}`)
};
