const { asyncHandler } = require("../utils/asyncHandler");
const meetingService = require("../services/meetingService");

module.exports = {
  create: asyncHandler(async (req, res) => res.status(201).json({ meeting: await meetingService.createMeeting(req.user._id, req.validated.body, { ipAddress: req.ip, userAgent: req.headers["user-agent"] }) })),
  list: asyncHandler(async (req, res) => res.json(await meetingService.listMeetings(req.user._id, req.query))),
  get: asyncHandler(async (req, res) => res.json({ meeting: await meetingService.getMeetingByMeetingId(req.params.meetingId) })),
  update: asyncHandler(async (req, res) => res.json({ meeting: await meetingService.updateMeeting(req.params.meetingId, req.user._id, req.body) })),
  cancel: asyncHandler(async (req, res) => res.json({ meeting: await meetingService.cancelMeeting(req.params.meetingId, req.user._id) })),
  remove: asyncHandler(async (req, res) => res.json(await meetingService.deleteMeeting(req.params.meetingId, req.user._id))),
  end: asyncHandler(async (req, res) => res.json({ meeting: await meetingService.endMeeting(req.params.meetingId, req.user._id) })),
  token: asyncHandler(async (req, res) => res.json(await meetingService.generateParticipantToken({
    meetingId: req.params.meetingId,
    userId: req.user?._id,
    guestName: req.body.guestName || req.body.name || req.body.displayName,
    guestEmail: req.body.email,
    password: req.body.password
  }))),
  waitingList: asyncHandler(async (req, res) => res.json({ participants: await meetingService.listWaitingParticipants(req.params.meetingId) })),
  admitWaiting: asyncHandler(async (req, res) => res.json({ admitted: true, identity: req.body.identity, result: await meetingService.admitWaitingParticipant(req.params.meetingId, req.body.identity) })),
  rejectWaiting: asyncHandler(async (req, res) => res.json({ rejected: true, identity: req.body.identity, result: await meetingService.rejectWaitingParticipant(req.params.meetingId, req.body.identity) })),
  admitAllWaiting: asyncHandler(async (req, res) => res.json({ count: await meetingService.admitAllWaiting(req.params.meetingId) })),
  participants: asyncHandler(async (req, res) => res.json({ participants: await meetingService.listCurrentParticipants(req.params.meetingId) })),
  removeParticipant: asyncHandler(async (req, res) => res.json({ removed: true, result: await meetingService.removeCurrentParticipant(req.params.meetingId, req.body.identity) })),
  muteParticipant: asyncHandler(async (req, res) => res.json({ result: await meetingService.muteParticipant(req.params.meetingId, req.body.identity, req.body.trackSid, req.body.muted) })),
  addCoHost: asyncHandler(async (req, res) => res.json({ meeting: await meetingService.addCoHost(req.params.meetingId, req.body.userId) })),
  removeCoHost: asyncHandler(async (req, res) => res.json({ meeting: await meetingService.removeCoHost(req.params.meetingId, req.params.userId) })),
  lock: asyncHandler(async (req, res) => res.json({ meeting: await meetingService.setMeetingLock(req.params.meetingId, true) })),
  unlock: asyncHandler(async (req, res) => res.json({ meeting: await meetingService.setMeetingLock(req.params.meetingId, false) })),
  raiseHand: asyncHandler(async (req, res) => res.json({ ok: await meetingService.raiseHand(req.params.meetingId, req.user._id) })),
  lowerHand: asyncHandler(async (req, res) => res.json({ ok: await meetingService.lowerHand(req.params.meetingId, req.user._id) })),
  listHands: asyncHandler(async (req, res) => res.json({ hands: await meetingService.listRaisedHands(req.params.meetingId) })),
  react: asyncHandler(async (req, res) => res.json({ meeting: await meetingService.addReaction(req.params.meetingId, req.body.participantId, req.body.emoji) })),
  createBreakouts: asyncHandler(async (req, res) => res.status(201).json({ rooms: await meetingService.createBreakoutRooms(req.params.meetingId, req.body.rooms) })),
  closeBreakouts: asyncHandler(async (req, res) => res.json({ ok: await meetingService.closeBreakoutRooms(req.params.meetingId) })),
  createPoll: asyncHandler(async (req, res) => res.status(201).json({ poll: await meetingService.createPoll(req.params.meetingId, req.user._id, req.body) })),
  respondPoll: asyncHandler(async (req, res) => res.status(201).json({ response: await meetingService.respondToPoll(req.params.pollId, req.body) })),
  pollResults: asyncHandler(async (req, res) => res.json(await meetingService.getPollResults(req.params.pollId))),
  endPoll: asyncHandler(async (req, res) => res.json({ poll: await meetingService.endPoll(req.params.pollId) })),
  createQuestion: asyncHandler(async (req, res) => res.status(201).json({ question: await meetingService.submitQuestion(req.params.meetingId, { ...req.body, asker: req.user?._id }) })),
  listQuestions: asyncHandler(async (req, res) => res.json({ questions: await meetingService.listQuestions(req.params.meetingId) })),
  upvoteQuestion: asyncHandler(async (req, res) => res.json({ question: await meetingService.upvoteQuestion(req.params.questionId, req.user._id) })),
  answerQuestion: asyncHandler(async (req, res) => res.json({ question: await meetingService.answerQuestion(req.params.questionId, req.body.answerText, req.body.isPublic) })),
  dismissQuestion: asyncHandler(async (req, res) => res.json({ question: await meetingService.dismissQuestion(req.params.questionId) })),
  sendChat: asyncHandler(async (req, res) => res.status(201).json({ message: await meetingService.sendChatMessage(req.params.meetingId, { userId: req.user?._id, guestName: req.body.guestName }, req.body) })),
  uploadChat: asyncHandler(async (req, res) => res.status(201).json({ message: await meetingService.uploadChatFile(req.params.meetingId, { userId: req.user?._id, guestName: req.body.guestName }, req.file, req.body) })),
  listChat: asyncHandler(async (req, res) => res.json({ messages: await meetingService.listChatMessages(req.params.meetingId, req.user?._id) })),
  deleteChat: asyncHandler(async (req, res) => res.json({ message: await meetingService.deleteChatMessage(req.params.messageId) })),
  pinChat: asyncHandler(async (req, res) => res.json({ message: await meetingService.pinChatMessage(req.params.messageId, req.body.isPinned) })),
  getWhiteboard: asyncHandler(async (req, res) => res.json({ whiteboard: await meetingService.getWhiteboard(req.params.meetingId) })),
  updateWhiteboard: asyncHandler(async (req, res) => res.json({ whiteboard: await meetingService.updateWhiteboard(req.params.meetingId, req.user?._id, req.body.canvasState) })),
  listTemplates: asyncHandler(async (req, res) => res.json({ templates: await meetingService.listTemplates(req.user._id) })),
  createTemplate: asyncHandler(async (req, res) => res.status(201).json({ template: await meetingService.createTemplate(req.user._id, req.body) })),
  updateTemplate: asyncHandler(async (req, res) => res.json({ template: await meetingService.updateTemplate(req.params.templateId, req.user._id, req.body) })),
  deleteTemplate: asyncHandler(async (req, res) => res.status(204).send(await meetingService.deleteTemplate(req.params.templateId, req.user._id))),
  listNotes: asyncHandler(async (req, res) => res.json({ notes: await meetingService.getNotes(req.params.meetingId) })),
  addNote: asyncHandler(async (req, res) => res.status(201).json({ note: await meetingService.addNote(req.params.meetingId, req.user._id, req.body.content) })),
  updateNote: asyncHandler(async (req, res) => res.json({ note: await meetingService.updateNote(req.params.noteId, req.user._id, req.body.content) })),
  deleteNote: asyncHandler(async (req, res) => res.status(204).send(await meetingService.deleteNote(req.params.noteId)))
};
