const dotenv = require("dotenv");

dotenv.config();

module.exports = {
  nodeEnv: process.env.NODE_ENV || "development",
  port: Number(process.env.PORT || 4000),
  mongoUri: process.env.MONGODB_URI,
  redisUrl: process.env.REDIS_URL,
  frontendUrl: process.env.FRONTEND_URL || "http://localhost:3000",
  appBaseUrl: process.env.APP_BASE_URL || "http://localhost:4000",
  jwtAccessSecret: process.env.JWT_ACCESS_SECRET || "access-secret",
  jwtRefreshSecret: process.env.JWT_REFRESH_SECRET || "refresh-secret",
  jwtAccessExpiry: process.env.JWT_ACCESS_EXPIRY || "15m",
  jwtRefreshExpiry: process.env.JWT_REFRESH_EXPIRY || "7d",
  stripeSecretKey: process.env.STRIPE_SECRET_KEY || "",
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET || "",
  livekitUrl: process.env.LIVEKIT_URL || "",
  livekitApiKey: process.env.LIVEKIT_API_KEY || "",
  livekitApiSecret: process.env.LIVEKIT_API_SECRET || "",
  livekitWebhookSecret: process.env.LIVEKIT_WEBHOOK_SECRET || "",
  openAiApiKey: process.env.OPENAI_API_KEY || "",
  openAiModel: process.env.OPENAI_MODEL || "gpt-4o",
  encryptionSecret: process.env.ENCRYPTION_SECRET || "12345678901234567890123456789012",
  smtpHost: process.env.SMTP_HOST || "",
  smtpPort: Number(process.env.SMTP_PORT || 587),
  smtpUser: process.env.SMTP_USER || "",
  smtpPass: process.env.SMTP_PASS || "",
  emailFrom: process.env.EMAIL_FROM || "Onnonn <no-reply@onnonn.app>",
  cloudinaryCloudName: process.env.CLOUDINARY_CLOUD_NAME || "",
  cloudinaryApiKey: process.env.CLOUDINARY_API_KEY || "",
  cloudinaryApiSecret: process.env.CLOUDINARY_API_SECRET || "",
  googleClientId: process.env.GOOGLE_CLIENT_ID || "",
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET || "",
  googleRedirectUri: process.env.GOOGLE_REDIRECT_URI || "",
  googleOAuthScope: process.env.GOOGLE_OAUTH_SCOPE || "openid email profile https://www.googleapis.com/auth/calendar",
  firebaseProjectId: process.env.FIREBASE_PROJECT_ID || "",
  firebasePrivateKey: process.env.FIREBASE_PRIVATE_KEY || "",
  firebaseClientEmail: process.env.FIREBASE_CLIENT_EMAIL || "",
  stripeFreePlanPriceId: process.env.STRIPE_FREE_PLAN_PRICE_ID || "price_free",
  stripeProPlanPriceId: process.env.STRIPE_PRO_PLAN_PRICE_ID || "price_pro",
  stripeBusinessPlanPriceId: process.env.STRIPE_BUSINESS_PLAN_PRICE_ID || "price_business",
  superadminEmail: process.env.SUPERADMIN_EMAIL || "admin@onnonn.app",
  s3BucketName: process.env.S3_BUCKET_NAME || "",
  s3Region: process.env.S3_REGION || "",
  s3AccessKey: process.env.S3_ACCESS_KEY || "",
  s3SecretKey: process.env.S3_SECRET_KEY || "",
  samlAudience: process.env.SAML_AUDIENCE || "onnonn-sp",
  samlAcsUrl: process.env.SAML_ACS_URL || "http://localhost:4000/api/v1/auth/saml/callback"
};
